added broadcast again
teeworlds/teeworlds pull request #1694
Opened 2018-11-18 17:25 UTC by fokkonaut

you can go to the next line by using \n inside the text and the whole broadcast also gets printed to f1 console.

thanks to chilledragon for compiling and testing on mac :)

2018-11-18 17:35 UTC, ChillerDragon requested changes

2018-11-18 17:35 UTC, ChillerDragon commented on src/game/client/components/broadcast.cpp
> +	if (MsgType == NETMSGTYPE_SV_BROADCAST)
```suggestion
	if(MsgType == NETMSGTYPE_SV_BROADCAST)
```

2018-11-18 17:35 UTC, ChillerDragon commented on src/game/client/components/broadcast.cpp
> +	for (i = 0, ii = 0; i < str_length(m_aBroadcastText); i++)
```suggestion
	for(i = 0, ii = 0; i < str_length(m_aBroadcastText); i++)
```

2018-11-18 17:35 UTC, ChillerDragon commented on src/game/client/components/broadcast.cpp
> +		if (m_aBroadcastText[i] == '\n')
```suggestion
		if(m_aBroadcastText[i] == '\n')
```

2018-11-18 17:35 UTC, ChillerDragon commented on src/game/client/components/broadcast.cpp
> +			if (aBuf[0])
```suggestion
			if(aBuf[0])
```

2018-11-18 17:35 UTC, ChillerDragon commented on src/game/client/components/broadcast.cpp
> +	if (aBuf[0])
```suggestion
	if(aBuf[0])
```

2018-11-18 17:35 UTC, ChillerDragon commented on src/game/server/gamecontext.cpp
> +	for (i = 0, j = 0; aBuf[i]; i++, j++)
```suggestion
	for(i = 0, j = 0; aBuf[i]; i++, j++)
```

2018-11-18 17:35 UTC, ChillerDragon commented on src/game/server/gamecontext.cpp
> +		if (aBuf[i] == '\\' && aBuf[i + 1] == 'n')
```suggestion
		if(aBuf[i] == '\\' && aBuf[i + 1] == 'n')
```

2018-11-18 17:35 UTC, ChillerDragon commented on src/game/server/gamecontext.cpp
> +		else if (i != j)
```suggestion
		else if(i != j)
```

2018-11-18 17:36 UTC, oy commented
Won't be added that way. The DoBroadcast rendering area is reserved for client-sided notification now and nothing gonna interfere with that.

2018-11-18 17:40 UTC, ChillerDragon commented
@oy what do you suggest doing then?

2018-11-18 18:09 UTC, oy commented
@ChillerDragon not sure. Needs some thinking.

2018-11-18 21:33 UTC, nheir commented
Maybe duplicating broadcast to have "GameMessage" and "Broadcast" where "GameMessage" is client build message as now, and Broadcast is the server build message.
Either with a exclusion (ir GameMessage forbidding Broadcast) or in slightly different zone so the messages can't overlap and may be distinguished (different font, straight vs italic...)

2018-11-18 22:01 UTC, Dune-jr commented
`DoBroadcast` is actually used little (2 times), a lot of the text printing is done manually with adjusted parameters.

>Either with a exclusion (ir GameMessage forbidding Broadcast) or in slightly different zone so the messages can't overlap and may be distinguished (different font, straight vs italic...)

I agree. Maybe server broadcast could be some **smaller** text (in between the timer and the current warmup?). It should probably be made clear, by one way or another, that it is a custom text sent by the server and not a client message.

I think they still have their places in the game though - after all the `say` server messages are still around for custom uses.

2018-11-19 14:18 UTC, oy commented
Different area probably best.

2018-11-20 08:00 UTC, ChillerDragon commented
Imo the old broadcast area was pretty good. What about removing the broadcast if other messages appear?

2018-11-20 12:57 UTC, Dune-jr commented
Can we look for compromises instead of resisting to just about any change? @ChillerDragon

2018-11-20 15:22 UTC, oy commented
Putting it at the old spot means it will never show up f.e. in warmups, pauses and most of the time in survival.

2018-11-26 18:26 UTC, closed without merging