Allow editor switch entities
teeworlds/teeworlds pull request #3236
Opened 2024-03-01 11:36 UTC by Bamcane

### Why
Many mods have their own entities.In the past, if we needed to switch the entities, we need use the mod's entities.png to take the vanilla entities.png. Also, it spent more time to switch entities. 
This PR solve that problem, be different from DDNet, mapper put their entities images in %APPDATA%/editor, and they need to press this button to open a file dialog
![Screenshot](https://github.com/teeworlds/teeworlds/assets/65482653/000447b4-14b1-4135-95c7-29add5573c46)
Then they could choose entities files
![Screenshot](https://github.com/teeworlds/teeworlds/assets/65482653/2c8ee449-063e-437e-b254-5beee2973069)
The **Vanilla** entities file is a link of data/editor/entities.png

2024-04-09 04:26 UTC, jtbx requested changes
Looks good for the most part, just a few nitpicks.

The commit message is a bit unclear, it should be reworded to "Allow switching the editor's entities". Make your changes and run `git commit --amend`.

2024-04-09 04:26 UTC, jtbx commented on src/game/editor/editor.cpp
> +	if((ImgInfo.m_Width % 16) || (ImgInfo.m_Height % 16))
You can remove these brackets
```suggestion
	if(ImgInfo.m_Width % 16 || ImgInfo.m_Height % 16)
```

2024-04-09 04:26 UTC, jtbx commented on src/game/editor/popups.cpp
> +		pEditor->UI()->DoLabel(&Label, "The width or height of the entities texture is not divisible by 16", 10.0f, TEXTALIGN_LEFT);
```suggestion
		pEditor->UI()->DoLabel(&Label, "The dimensions of the entities image are not divisible by 16", 10.0f, TEXTALIGN_LEFT);
```

2024-04-09 04:26 UTC, jtbx commented on src/game/editor/popups.cpp
> +	if(pEditor->DoButton_MenuItem(&s_EntitiesButton, "Load Entities", 0, &Slot, 0, "Load a image as the editor game entities"))
"Load entities" looks much more natural
```suggestion
	if(pEditor->DoButton_MenuItem(&s_EntitiesButton, "Load entities", 0, &Slot, 0, "Load an image as the editor's game entities"))
```

2025-08-10 06:38 UTC, closed without merging

2025-08-10 07:51 UTC, ChillerDragon commented
Why close @Bamcane

2025-08-10 08:30 UTC, Bamcane commented
I think that we have had this feature in the editor2, and also it seemed that oy want us to develop the editor2 instead of the editor of master branch.